apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oap
  name: oap-srv
  namespace: skywalking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oap
  template:
    metadata:
      labels:
        app: oap
      annotations:
    spec:
      serviceAccountName: skywalking-oap
      containers:
      - name: oap
        image: "harbor-cz.deepblueai.com/apache/skywalking-oap-server:7.0.0-es7"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 12800
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 12800
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 11800
          name: grpc
        - containerPort: 12800
          name: rest
        resources:
          requests:
            memory: 8Gi
            cpu: 8
        env:
        - name: JAVA_OPTS
          value: "-Xmx2g -Xms2g"
        - name: SW_CLUSTER
          value: kubernetes
        - name: SW_CLUSTER_K8S_NAMESPACE
          value: "skywalking"
        - name: SW_CLUSTER_K8S_LABEL
          value: "app=oap"
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: SW_STORAGE
          value: elasticsearch7
        - name: SW_STORAGE_ES_CLUSTER_NODES
          value: elasticsearch:9200
#         - name: SW_ES_USER
#           value: "skywalking"
#         - name: SW_ES_PASSWORD
#           value: "password"
        volumeMounts:
        - name: config
          mountPath: /skywalking/config
      volumes:
      - name: config
        configMap:
          name: oap-config
