apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  labels:
    app: zookeeper
spec:
  serviceName: {{ template "zookeeper.headless" . }}
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "zookeeper:3.5.5"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -xec
            - /config-scripts/run
          ports:
            - name: client
              containerPort: 2181
              protocol: TCP
            - name: election
              containerPort: 3888
              protocol: TCP
            - name: server
              containerPort: 2888
              protocol: TCP              
          livenessProbe:
            exec:
              command:
                - sh
                - /config-scripts/ok
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 2
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - sh
                - /config-scripts/ready
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 2
            successThreshold: 1
          env:
            - name: ZK_REPLICAS
              value: 3
            - name: ZOO_PORT
              value: 2181
            - name: ZOO_INIT_LIMIT
              value: 5
            - name: ZOO_STANDALONE_ENABLED
              value: false                            
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config-scripts
      volumes:
        - name: config
          configMap:
            name: zk-config
            defaultMode: 0555
        - name: data
          emptyDir: {}
