apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
    name: node-exporter
  selector:
    app: node-exporter
