apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aiplatform-server
  name: aiplatform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiplatform-server
  template:
    metadata:
      labels:
        app: aiplatform-server
    spec:
      containers:
      - env:
#        - name: JAVA_AGENT_OPTS
#          value: -javaagent:/aiplatform/agent/skywalking-agent.jar -Dskywalking.collector.backend_service=oap.skywalking:11800
#            -Dskywalking.agent.service_name=aiplatform
        - name: JVM_OPTS
          value: "-XX:+UseG1GC -XX:+PrintGCDetails -Xmn2048m -Xms4G -Xmx4G  -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=256M"
        - name: com.alibaba.nacos.naming.log.level
          value: "warn"
        - name: spring.profiles.active
          value: "test"
        - name: spring.redis.model
          value: "single"
        image: "10.16.32.59:1180/library/aiplatform:V189"
        imagePullPolicy: Always
        name: aiplatform
        resources:
          limits:
            cpu: "4"
            memory: 4000Mi
