apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aicontrol-server
  name: aicontrol
#  namespace: uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aicontrol-server
  template:
    metadata:
      labels:
        app: aicontrol-server
    spec:
      containers:
      - env:
        - name: JVM_OPTS
          value: -XX:+UseG1GC -Xmn2048m -Xms4G -Xmx4G  -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=256M
        - name: com.alibaba.nacos.naming.log.level
          value: warn
        - name: spring.profiles.active
          value: test
        image: 10.16.32.59:1180/library/aicontrol:V29
        imagePullPolicy: Always
        name: aicontrol
        resources:
          limits:
            cpu: "4"
            memory: 4000Mi

