apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-server
  name: mysql-57
spec:
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: deepblue2019
        image: ccr.ccs.tencentyun.com/deepblue/mysql:5.7
        imagePullPolicy: Always
        name: mysql-57
        ports:
        - containerPort: 3306
          name: 3306tcp300291
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vol1
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /opt/mysql5.7/
          type: ""
        name: vol1
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-server
  name: mysql-57
spec:
  ports:
  - name: mysql-57
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-server
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-server
  name: mysql-57-nodeport
spec:
  ports:
  - name: 3306tcp300291
    nodePort: 30029
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-server
