apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aiplatform-web-server
  name: aiplatform-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiplatform-web-server
  template:
    metadata:
      labels:
        app: aiplatform-web-server
    spec:
      containers:
      - env:
        - name: JVM_OPTS
          value: "-XX:+UseG1GC -Xmn2048m -Xms4G -Xmx4G -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=256M -XX:+PrintGCDetails"
        - name: com.alibaba.nacos.naming.log.level
          value: "warn"
        - name: spring.profiles.active
          value: "test"
        - name: spring.redis.model
          value: "single"
        - name: spring.cloud.nacos.discovery.server-addr
          value: "nacos-server.component:8848"
        - name: spring.cloud.nacos.config.server-addr
          value: "nacos-server.component:8848"                      
        image: ccr.ccs.tencentyun.com/deepblue/aiplatform-web:v1
        imagePullPolicy: Always
        name: aiplatform-web
        resources:
          limits:
            cpu: "4"
            memory: 4000Mi
