apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-server
  name: admin
#  namespace: uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - env:
        - name: com.alibaba.nacos.naming.log.level
          value: warn
        - name: spring.profiles.active
          value: test
        image: 10.16.32.59:1180/library/admin:V17
        imagePullPolicy: Always
        name: admin
        ports:
        - containerPort: 8090
          name: svc
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 4000Mi
